[dev]
publish = "website/static"
functions = "api"

[build]
publish = "website/static"
command = "make build"
functions = "api"

[[redirects]]
from = "/health"
to = "/.netlify/functions/health"
status = 200

[[redirects]]
from = "/experience"
to = "/.netlify/functions/experience"
status = 200

[[redirects]]
from = "/projects"
to = "/.netlify/functions/projects"
status = 200

[build.environment]
GO_VERSION = "1.22.2"
GO_IMPORT_PATH = "github.com/NDoolan360/go-htmx-site"
GO111MODULE = "on"

[[plugins]]
package = "@netlify/plugin-sitemap"
[plugins.inputs]
buildDir = "website/static"
