[dev]
publish = "dist"
framework = "#static"
functions = "api"

[build]
publish = "dist"
command = "make dist"
functions = "api"

[[redirects]]
from = "/health"
to = "/.netlify/functions/health"
status = 200

[[redirects]]
from = "/experience"
to = "/.netlify/functions/experience"
status = 200

[[redirects]]
from = "/projects"
to = "/.netlify/functions/projects"
status = 200

[build.environment]
GO_VERSION = "1.22.5"
GO_IMPORT_PATH = "github.com/NDoolan360/go-htmx-site"
GO111MODULE = "on"

[[plugins]]
package = "@netlify/plugin-sitemap"
[plugins.inputs]
buildDir = "dist"
filePath = "sitemap.xml"

[[plugins]]
package = "@netlify/plugin-lighthouse"
[plugins.inputs]
fail_deploy_on_score_thresholds = "true"
[plugins.inputs.thresholds]
performance = 0.9
accessibility = 0.9
best-practices = 0.9
seo = 0.5
