[build]
publish = "static"
command = "make build-linux"
functions = "api"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"

[build.environment]
GO_VERSION = "1.21.5"
GO_IMPORT_PATH = "github.com/NDoolan360/go-htmx-site"
GO111MODULE = "on"
