name: Continuous Integration

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - master

jobs:
    bun:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: 1.0.15

            - name: Cache Node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: bun-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: bun-

            - run: bun install
            - run: bun ci
