name: Continuous Integration

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - master

jobs:
    node:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Cache Node modules
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: npm-${{ runner.os }}-

            - run: npm ci
            - run: npm run lint:ts
            - run: npm run lint:css
            - run: npm run format
            - run: npm run test
