name: Continuous Integration

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - master

jobs:
    bun:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version: 1.20.2

            - name: Go Lint
              uses: golangci/golangci-lint-action@v3
              with:
                version: v1.55

            - name: Run Go Tests
              run: go test ./test
