name: Continuous Integration

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - master

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                directory: [api/health, api/projects, website]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: 1.22.2
            - name: Generate Templates
              run: make templates
            - name: Lint
              uses: golangci/golangci-lint-action@v5
              with:
                  version: v1.55.2
                  working-directory: ${{ matrix.directory }}

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: 1.22.2
            - name: Test
              run: make test
