name: Continuous Integration

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - master

jobs:
    bun:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Biome
              uses: biomejs/setup-biome@v1
              with:
                version: 1.4.1

            - name: Run Biome CI
              run: biome ci .

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version: 1.20.2

            - name: Run Go Tests
              run: go test
